package com.funi.platform.lshc.entity;

import java.util.Date;

public class AccountBizEntity extends BaseEntity{

    /**
     * 监管编号
     */
    private String supCode;

    /**
     * 业务件号
     */
    private String bizNo;

    /**
     * 业务类型：账户新增、变更
     */
    private String bizType;

    /**
     * 业务状态：初审、复审、办结
     */
    private String status;

    /**
     * 提交日期
     */
    private Date submitDate;
    /**
     * 办结日期
     */
    private Date settingTime;

    /**
     * 审核日期
     */
    private Date auditTime;

    /**
     * 上一笔业务件号
     */
    private String preBizNo;

    /**
     * 是否有效
     */
    private String isvalide;

    /**
     * 逻辑区域编号
     */
    private Long regionCode;

    /**
     * 机构编码
     */
    private String orgCode;
    //状态
    private String statusInchinese;
    //上一笔业务件id
    private String lastId;
    //变更类型
    private int changeType;

    public int getChangeType() {
        return changeType;
    }

    public void setChangeType(int changeType) {
        this.changeType = changeType;
    }

    public Date getSettingTime() {
        return settingTime;
    }

    public void setSettingTime(Date settingTime) {
        this.settingTime = settingTime;
    }

    public Date getAuditTime() {
        return auditTime;
    }

    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    public String getLastId() {
        return lastId;
    }

    public void setLastId(String lastId) {
        this.lastId = lastId;
    }

    public String getStatusInchinese() {
        return statusInchinese;
    }

    public void setStatusInchinese(String statusInchinese) {
        this.statusInchinese = statusInchinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.SUP_CODE
     *
     * @return the value of PSFS_ACCOUNT_BIZ.SUP_CODE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public String getSupCode() {
        return supCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.SUP_CODE
     *
     * @param supCode the value for PSFS_ACCOUNT_BIZ.SUP_CODE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setSupCode(String supCode) {
        this.supCode = supCode == null ? null : supCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.BIZ_NO
     *
     * @return the value of PSFS_ACCOUNT_BIZ.BIZ_NO
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.BIZ_NO
     *
     * @param bizNo the value for PSFS_ACCOUNT_BIZ.BIZ_NO
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.BIZ_TYPE
     *
     * @return the value of PSFS_ACCOUNT_BIZ.BIZ_TYPE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.BIZ_TYPE
     *
     * @param bizType the value for PSFS_ACCOUNT_BIZ.BIZ_TYPE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.STATUS
     *
     * @return the value of PSFS_ACCOUNT_BIZ.STATUS
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.STATUS
     *
     * @param status the value for PSFS_ACCOUNT_BIZ.STATUS
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.SUBMIT_DATE
     *
     * @return the value of PSFS_ACCOUNT_BIZ.SUBMIT_DATE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public Date getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.SUBMIT_DATE
     *
     * @param submitDate the value for PSFS_ACCOUNT_BIZ.SUBMIT_DATE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.PRE_BIZ_NO
     *
     * @return the value of PSFS_ACCOUNT_BIZ.PRE_BIZ_NO
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public String getPreBizNo() {
        return preBizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.PRE_BIZ_NO
     *
     * @param preBizNo the value for PSFS_ACCOUNT_BIZ.PRE_BIZ_NO
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setPreBizNo(String preBizNo) {
        this.preBizNo = preBizNo == null ? null : preBizNo.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.ISVALIDE
     *
     * @return the value of PSFS_ACCOUNT_BIZ.ISVALIDE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public String getIsvalide() {
        return isvalide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.ISVALIDE
     *
     * @param isvalide the value for PSFS_ACCOUNT_BIZ.ISVALIDE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setIsvalide(String isvalide) {
        this.isvalide = isvalide == null ? null : isvalide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.REGION_CODE
     *
     * @return the value of PSFS_ACCOUNT_BIZ.REGION_CODE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public Long getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.REGION_CODE
     *
     * @param regionCode the value for PSFS_ACCOUNT_BIZ.REGION_CODE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setRegionCode(Long regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PSFS_ACCOUNT_BIZ.ORG_CODE
     *
     * @return the value of PSFS_ACCOUNT_BIZ.ORG_CODE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PSFS_ACCOUNT_BIZ.ORG_CODE
     *
     * @param orgCode the value for PSFS_ACCOUNT_BIZ.ORG_CODE
     *
     * @mbggenerated Mon Jun 05 13:08:15 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

}