--Step 1:init LSHC system app code
insert into CF_APP (ID, NAME, CODE, DISCRIPTION, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, RPC_PORT)
values ('40', 'LSHC', 'lshc', null, 0, null, null, null, null, null, null, null, 6033);

--Step 2:init menu data
insert into cf_menu (ID, PARENT_ID, APP_ID, TYPE, SORT, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, NAME, URL, IS_IN_HOMEPAGE, MENU_DESC, MENU_BG_IMG_URL)
values ('2e6724ee-9150-4d07-ac9a-b07a30eb2f0c', '1', null, 'M', 0, 0, 1, to_date('01-06-2019 15:36:11', 'dd-mm-yyyy hh24:mi:ss'), null, null, 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', null, null, '房屋普查', null, null, null, null);
insert into cf_menu (ID, PARENT_ID, APP_ID, TYPE, SORT, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, NAME, URL, IS_IN_HOMEPAGE, MENU_DESC, MENU_BG_IMG_URL)
values ('34b3d2f1-601a-4dc5-b024-9ab1578763de', '5b13289b-2ebe-4210-b3e8-88d5d6416bd1', null, 'M', 2, 0, 1, to_date('01-06-2019 15:44:13', 'dd-mm-yyyy hh24:mi:ss'), null, null, 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', null, null, '已办件', '/lshc/getView?viewName=app.platform.lshc.view.regi.approve.DoneRegiMainView', null, null, null);
insert into cf_menu (ID, PARENT_ID, APP_ID, TYPE, SORT, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, NAME, URL, IS_IN_HOMEPAGE, MENU_DESC, MENU_BG_IMG_URL)
values ('5b13289b-2ebe-4210-b3e8-88d5d6416bd1', '2e6724ee-9150-4d07-ac9a-b07a30eb2f0c', null, 'M', 1, 0, 1, to_date('01-06-2019 15:42:46', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-06-2019 19:44:01', 'dd-mm-yyyy hh24:mi:ss'), null, 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', null, '普查管理', '/lshc/getView?viewName=app.platform.lshc.view.regi.home.HomeMainView', null, null, null);
insert into cf_menu (ID, PARENT_ID, APP_ID, TYPE, SORT, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, NAME, URL, IS_IN_HOMEPAGE, MENU_DESC, MENU_BG_IMG_URL)
values ('6f324633-5b94-4515-b0ff-39b6256a52b4', '5b13289b-2ebe-4210-b3e8-88d5d6416bd1', null, 'M', 0, 0, 1, to_date('01-06-2019 15:43:22', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-06-2019 04:03:12', 'dd-mm-yyyy hh24:mi:ss'), null, 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', null, '普查录入', '/lshc/getView?viewName=app.platform.lshc.view.regi.manage.RegiMainView', null, null, null);
insert into cf_menu (ID, PARENT_ID, APP_ID, TYPE, SORT, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, NAME, URL, IS_IN_HOMEPAGE, MENU_DESC, MENU_BG_IMG_URL)
values ('bd22c96a-33fd-454f-8aff-57a0450f57fa', '5b13289b-2ebe-4210-b3e8-88d5d6416bd1', null, 'M', 1, 0, 1, to_date('01-06-2019 15:43:49', 'dd-mm-yyyy hh24:mi:ss'), null, null, 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', null, null, '待办件', '/lshc/getView?viewName=app.platform.lshc.view.regi.approve.ToDoRegiMainView', null, null, null);
insert into cf_menu (ID, PARENT_ID, APP_ID, TYPE, SORT, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, NAME, URL, IS_IN_HOMEPAGE, MENU_DESC, MENU_BG_IMG_URL)
values ('f1419099-3aa4-4440-988c-32870043bf2b', '5b13289b-2ebe-4210-b3e8-88d5d6416bd1', null, 'M', 3, 0, 1, to_date('01-06-2019 15:44:34', 'dd-mm-yyyy hh24:mi:ss'), null, null, 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', null, null, '综合查询', '/lshc/getView?viewName=app.platform.lshc.view.regi.query.QueryMainView', null, null, null);

--Step 3: init authority data
insert into cf_authority (ID, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, NAME, CODE, MENU_ID)
values ('69558d26-ea9a-4e67-bc26-245ce79e38d4', 0, 1, to_date('26-06-2019 19:48:19', 'dd-mm-yyyy hh24:mi:ss'), null, null, 'c3dd9aa3-0dd8-46ea-875c-5cd66f8dd73a', null, null, '退回', 'AUTH_LSHC_QUERY_TH_BTN', 'f1419099-3aa4-4440-988c-32870043bf2b');

--Step 4: init workflow conclusions
insert into AUDIT_CONCLUSIONS (ID, NAME, CODE, IS_CALL_WORKFLOW, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, SORT)
values ('41', '初审不通过', 'CSBTG', 1, 0, 1, null, null, null, null, null, null, 9);
insert into AUDIT_CONCLUSIONS (ID, NAME, CODE, IS_CALL_WORKFLOW, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, SORT)
values ('42', '复审不通过', 'FSBTG', 1, 0, 1, null, null, null, null, null, null, 9);
insert into AUDIT_CONCLUSIONS (ID, NAME, CODE, IS_CALL_WORKFLOW, IS_DELETED, VERSION, SYS_CREATE_TIME, SYS_UPDATE_TIME, SYS_DELETE_TIME, SYS_CREATE_ID, SYS_UPDATE_ID, SYS_DELETE_ID, SORT)
values ('43', '结束', 'JS', 1, 0, 1, null, null, null, null, null, null, 9);

--Step 5: init dic data
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB2A00D0E053AC1DFBCECC71', '是', '是', 'WHETHER', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB2B00D0E053AC1DFBCECC71', '一', '一', 'HOUSE_STYLE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB2C00D0E053AC1DFBCECC71', '否', '否', 'WHETHER', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB2D00D0E053AC1DFBCECC71', '二', '二', 'HOUSE_STYLE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB2E00D0E053AC1DFBCECC71', '三', '三', 'HOUSE_STYLE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB2F00D0E053AC1DFBCECC71', '2000', '2000', 'BUILD_YEAR', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3000D0E053AC1DFBCECC71', '2001', '2001', 'BUILD_YEAR', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3100D0E053AC1DFBCECC71', '商品房', '商品房', 'HOUSE_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3200D0E053AC1DFBCECC71', '周转房', '周转房', 'HOUSE_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3300D0E053AC1DFBCECC71', '经济房', '经济房', 'HOUSE_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3400D0E053AC1DFBCECC71', '公租房', '公租房', 'HOUSE_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3500D0E053AC1DFBCECC71', '自建房', '自建房', 'HOUSE_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3600D0E053AC1DFBCECC71', '框剪', '框剪', 'HOUSE_STRUCTURE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3700D0E053AC1DFBCECC71', '框架', '框架', 'HOUSE_STRUCTURE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3800D0E053AC1DFBCECC71', '砖混', '砖混', 'HOUSE_STRUCTURE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3900D0E053AC1DFBCECC71', '土木', '土木', 'HOUSE_STRUCTURE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3A00D0E053AC1DFBCECC71', '其他', '其他', 'HOUSE_STRUCTURE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3B00D0E053AC1DFBCECC71', '住宅', '住宅', 'HOUSE_USE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3C00D0E053AC1DFBCECC71', '商业', '商业', 'HOUSE_USE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3D00D0E053AC1DFBCECC71', '写字楼', '写字楼', 'HOUSE_USE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3E00D0E053AC1DFBCECC71', '车位', '车位', 'HOUSE_USE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB3F00D0E053AC1DFBCECC71', '其他', '其他', 'HOUSE_USE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4000D0E053AC1DFBCECC71', '国有', '国有', 'LAND_NATURE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4100D0E053AC1DFBCECC71', '集体', '集体', 'LAND_NATURE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4200D0E053AC1DFBCECC71', '清水', '清水', 'FIT_STATUS', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4300D0E053AC1DFBCECC71', '简装', '简装', 'FIT_STATUS', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4400D0E053AC1DFBCECC71', '精装', '精装', 'FIT_STATUS', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4500D0E053AC1DFBCECC71', '产权人', '产权人', 'ENT_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4600D0E053AC1DFBCECC71', '所有人', '所有人', 'ENT_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4600D0E053AC1DFBCECC72', '使用人', '使用人', 'ENT_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4600D0E053AC1DFBCECC73', '租客', '租客', 'ENT_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4600D0E053AC1DFBCECC74', '其他', '其他', 'ENT_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4700D0E053AC1DFBCECC71', '男', '男', 'GENDER', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4800D0E053AC1DFBCECC71', '女', '女', 'GENDER', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4900D0E053AC1DFBCECC71', '汉族', '汉族', 'ENT_NATION', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4A00D0E053AC1DFBCECC71', '藏族', '藏族', 'ENT_NATION', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4B00D0E053AC1DFBCECC71', '四川成都', '四川成都', 'ENT_NATIVE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4C00D0E053AC1DFBCECC71', '西藏拉萨', '西藏拉萨', 'ENT_NATIVE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4D00D0E053AC1DFBCECC71', '未婚', '未婚', 'MARRIAGE_STATUS', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4E00D0E053AC1DFBCECC71', '已婚', '已婚', 'MARRIAGE_STATUS', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB4F00D0E053AC1DFBCECC71', '身份证', '身份证', 'ID_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB5000D0E053AC1DFBCECC71', '其他', '其他', 'ID_TYPE', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB5100D0E053AC1DFBCECC71', '职员', '职员', 'CAREER', NULL, '1', NULL);
INSERT INTO "EISTRONG"."LSHC_DICTIONARY"("ID", "NAME", "FORMER_NAME", "CONFIG_TYPE", "PID", "ISONLINE", "NOTE") VALUES ('8BF63B69FB5200D0E053AC1DFBCECC71', '无业', '无业', 'CAREER', NULL, '1', NULL);
