--拉萨市城镇住房普查统计表（一）,需要使用数据权限code替换SQL中的区域编码
SELECT
	tt.UNIT_NAME AS 填报单位,
	tt.REPORT_DATE AS 填报时间,
	tt.STREET AS 街道,
	tt.COMMUNITY_NAME AS 社区名称,
	tt.PROJECT_NAME AS 小区名称,
	tt.ADDRESS AS 小区坐落,
	SUM( tt.BUILD_COUNT ) AS 楼栋总数,
	SUM( tt.UNIT_COUNT ) AS 单元总数,
	SUM( tt.HOUSE_COUNT ) AS 总户数,
	tt.BUILD_DATE AS 建成年份,
	tt.ESTATE_UNIT_NAME AS 物业管理单位名称
FROM
	(
	SELECT
		UNIT_NAME AS UNIT_NAME,
		STREET AS STREET,
		COMMUNITY_NAME AS COMMUNITY_NAME,
		PROJECT_NAME AS PROJECT_NAME,
		ADDRESS AS ADDRESS,
		0 AS BUILD_COUNT,
		0 AS UNIT_COUNT,
		count( 1 ) AS HOUSE_COUNT,
		REPORT_DATE AS REPORT_DATE,
		BUILD_DATE AS BUILD_DATE,
		ESTATE_UNIT_NAME AS ESTATE_UNIT_NAME
	FROM
		(
		SELECT
			t1.MAP_CODE,
			t2.UNIT_NAME,
			t1.STREET,
			t1.COMMUNITY_NAME,
			t1.PROJECT_NAME,
			t1.ADDRESS,
			t2.REPORT_DATE,
			t2.BUILD_DATE,
			t2.ESTATE_UNIT_NAME,
			t2.BUILD_NO,
			t2.UNIT_NO,
			t2.ROOM_NO
		FROM
			LSHC_BUILD_INFO t1
			INNER JOIN LSHC_REGI_INFO t2 ON t1.MAP_CODE = t2.MAP_CODE
		WHERE
			t1.DELETED = 0
			AND t1.ISVALIDE = '1'
			AND t2.DELETED = 0
			AND t2.ISVALIDE = '1'
			AND t2.COMMON IN ( '54010200401', '54010200401' )
		GROUP BY
			t1.MAP_CODE,
			t2.UNIT_NAME,
			t1.STREET,
			t1.COMMUNITY_NAME,
			t1.PROJECT_NAME,
			t1.ADDRESS,
			t2.REPORT_DATE,
			t2.BUILD_DATE,
			t2.ESTATE_UNIT_NAME,
			t2.BUILD_NO,
			t2.UNIT_NO,
			t2.ROOM_NO
		ORDER BY
			t2.REPORT_DATE
		)
	GROUP BY
		UNIT_NAME,
		STREET,
		COMMUNITY_NAME,
		PROJECT_NAME,
		ADDRESS,
		REPORT_DATE,
		BUILD_DATE,
		ESTATE_UNIT_NAME UNION ALL
	SELECT
		UNIT_NAME AS UNIT_NAME,
		STREET AS STREET,
		COMMUNITY_NAME AS COMMUNITY_NAME,
		PROJECT_NAME AS PROJECT_NAME,
		ADDRESS AS ADDRESS,
		0 AS BUILD_COUNT,
		count( 1 ) AS UNIT_COUNT,
		0 AS HOUSE_COUNT,
		REPORT_DATE AS REPORT_DATE,
		BUILD_DATE AS BUILD_DATE,
		ESTATE_UNIT_NAME AS ESTATE_UNIT_NAME
	FROM
		(
		SELECT
			t1.MAP_CODE,
			t2.UNIT_NAME,
			t1.STREET,
			t1.COMMUNITY_NAME,
			t1.PROJECT_NAME,
			t1.ADDRESS,
			t2.REPORT_DATE,
			t2.BUILD_DATE,
			t2.ESTATE_UNIT_NAME,
			t2.BUILD_NO,
			t2.UNIT_NO
		FROM
			LSHC_BUILD_INFO t1
			INNER JOIN LSHC_REGI_INFO t2 ON t1.MAP_CODE = t2.MAP_CODE
		WHERE
			t1.DELETED = 0
			AND t1.ISVALIDE = '1'
			AND t2.DELETED = 0
			AND t2.ISVALIDE = '1'
			AND t2.COMMON IN ( '54010200401', '54010200401' )
		GROUP BY
			t1.MAP_CODE,
			t2.UNIT_NAME,
			t1.STREET,
			t1.COMMUNITY_NAME,
			t1.PROJECT_NAME,
			t1.ADDRESS,
			t2.REPORT_DATE,
			t2.BUILD_DATE,
			t2.ESTATE_UNIT_NAME,
			t2.BUILD_NO,
			t2.UNIT_NO
		ORDER BY
			t2.REPORT_DATE
		)
	GROUP BY
		UNIT_NAME,
		STREET,
		COMMUNITY_NAME,
		PROJECT_NAME,
		ADDRESS,
		REPORT_DATE,
		BUILD_DATE,
		ESTATE_UNIT_NAME UNION ALL
	SELECT
		UNIT_NAME AS UNIT_NAME,
		STREET AS STREET,
		COMMUNITY_NAME AS COMMUNITY_NAME,
		PROJECT_NAME AS PROJECT_NAME,
		ADDRESS AS ADDRESS,
		count( 1 ) AS BUILD_COUNT,
		0 AS UNIT_COUNT,
		0 AS HOUSE_COUNT,
		REPORT_DATE AS REPORT_DATE,
		BUILD_DATE AS BUILD_DATE,
		ESTATE_UNIT_NAME AS ESTATE_UNIT_NAME
	FROM
		(
		SELECT
			t1.MAP_CODE,
			t2.UNIT_NAME,
			t1.STREET,
			t1.COMMUNITY_NAME,
			t1.PROJECT_NAME,
			t1.ADDRESS,
			t2.REPORT_DATE,
			t2.BUILD_DATE,
			t2.ESTATE_UNIT_NAME,
			t2.BUILD_NO
		FROM
			LSHC_BUILD_INFO t1
			INNER JOIN LSHC_REGI_INFO t2 ON t1.MAP_CODE = t2.MAP_CODE
		WHERE
			t1.DELETED = 0
			AND t1.ISVALIDE = '1'
			AND t2.DELETED = 0
			AND t2.ISVALIDE = '1'
			AND t2.COMMON IN ( '54010200401', '54010200401' )
		GROUP BY
			t1.MAP_CODE,
			t2.UNIT_NAME,
			t1.STREET,
			t1.COMMUNITY_NAME,
			t1.PROJECT_NAME,
			t1.ADDRESS,
			t2.REPORT_DATE,
			t2.BUILD_DATE,
			t2.ESTATE_UNIT_NAME,
			t2.BUILD_NO
		ORDER BY
			t2.REPORT_DATE
		)
	GROUP BY
		STREET,
		UNIT_NAME,
		COMMUNITY_NAME,
		PROJECT_NAME,
		ADDRESS,
		REPORT_DATE,
		BUILD_DATE,
		ESTATE_UNIT_NAME
	) tt
GROUP BY
	UNIT_NAME,
	STREET,
	COMMUNITY_NAME,
	PROJECT_NAME,
	ADDRESS,
	REPORT_DATE,
	BUILD_DATE,
	ESTATE_UNIT_NAME
ORDER BY
	REPORT_DATE


--拉萨市城镇住房普查统计表（二）,需要使用数据权限code替换SQL中的区域编码
SELECT
	UNIT_NAME AS 填报单位,
	REPORT_DATE AS 填报时间,
	PROJECT_NAME AS 小区名称,
	COMMUNITY_NAME AS 社区,
	ESTATE_UNIT_NAME AS 物业管理单位名称,
	MAP_CODE AS 栋编号,
	UNIT_NO AS 单元号,
	LAYER AS 楼层号,
	ROOM_NO AS 房间号,
	RIGHT_ADDR AS 建筑面积,
	HOUSE_STRUCTURE AS 房屋结构,
	HOUSE_USE AS 房屋用途,
	HOUSE_TYPE AS 房屋类别,
	BUILD_DATE AS 建成年份,
	t2.ENT_NAME AS 权利人姓名,
	t2.ID_NO AS 权利人身份证号,
	IS_REGI AS 是否办理产权,
	RIGHT_NO AS 产权证号,
	LAND_STATUS AS 土地性质,
	FIT_STATUS AS 装修状态,
	IS_CHECK_IN AS 是否入住,
	IS_RENT AS 是否出租,
	PERSON_NUM AS 居住人员数量
FROM
	LSHC_REGI_INFO t1
	INNER JOIN LSHC_ENT_INFO t2 ON t1.ID = t2.HC_ID
WHERE
	t1.DELETED = 0
	AND t1.ISVALIDE = '1'
	AND t2.DELETED = 0
	AND t2.ISVALIDE = '1'
	AND t1.COMMON IN ( '54010200401', '54010200401' )
ORDER BY
	REPORT_DATE DESC

  delete from LSHC_BUILD_INFO;
  delete from LSHC_ENT_INFO;
  delete from LSHC_FILE;
  delete from LSHC_JOB_ACCEPT;
  delete from LSHC_JOB_LOG;
  delete from LSHC_REGI_INFO;